### ISSUE TITLE
opening hours, comments and free parking spaces are cut off also

### ISSUE THREAD

**Issue by d-wagner** [pmdhbw/parkplatz#21]
might be related to the payment issue

**Comment by enrico-kaack** [comment]
seem, that it is not provided by php, the loaded xml doc contains just the chars which are displayed

**Comment by d-wagner** [comment]
Torben already told me it has to do with field length with has to be increased on most of the fields.

**Comment by tkrieger** [comment]
fixed: [commit](https://github.com/pmdhbw/parkplatz/commit/d53a84f568199063537d366473b3c1cbc20a0ae8) - BUT: only works with app_dev.php/init not with app.php/init. Absolute no idea how to fix this probably something is cached her or so ...
