### ISSUE TITLE
performance bad on reloading backend

### ISSUE THREAD

**Issue by d-wagner** [pmdhbw/parkplatz#23]
When the backend reloads, page display is very slow.

Maybe the backend should return old data and then trigger reloading, only the next user would profit from reloading that but loading times of 10s are not acceptable.

**Comment by enrico-kaack** [comment]
Alternative would be to have a cron job running in backend to refresh it ad midnight.

**Comment by d-wagner** [comment]
Backend is now calling app.php/init function on load. Torben and me planned on doing the refresh here, slightly before the app.php/stations gets called and then rely on data integrity on the database to slip in the database request.

**Comment by d-wagner** [comment]
Init is now asynchronously called on loading of the site. This ensures better performance and works fine apparently, solved for now.
